/****************************************************************************
 ControlList.h

 Description:	Lynx Application Programming Interface Header File

 Created: David A. Hoatson, June 2003
	
 Copyright © 2003 Lynx Studio Technology, Inc.

 This software contains the valuable TRADE SECRETS and CONFIDENTIAL INFORMATION 
 of Lynx Studio Technology, Inc. The software is protected under copyright 
 laws as an unpublished work of Lynx Studio Technology, Inc.  Notice is 
 for informational purposes only and does not imply publication.  The user 
 of this software may make copies of the software for use with products 
 manufactured by Lynx Studio Technology, Inc. or under license from 
 Lynx Studio Technology, Inc. and for no other use.

 THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
 KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR
 PURPOSE.

 Environment: 

 4 spaces per tab

 Revision History
 
 When      Who  Description
 --------- ---  ------------------------------------------------------------
****************************************************************************/

#ifndef _CONTROLLIST_H
#define _CONTROLLIST_H

/////////////////////////////////////////////////////////////////////////////
//	Mixer Line Types
/////////////////////////////////////////////////////////////////////////////
enum
{
	// Destinations
	LINE_OUT_1=0,	// must be first destination line
	LINE_OUT_2,
	LINE_OUT_3,
	LINE_OUT_4,
	LINE_OUT_5,
	LINE_OUT_6,
	LINE_OUT_7,
	LINE_OUT_8,
	LINE_OUT_9,
	LINE_OUT_10,
	LINE_OUT_11,
	LINE_OUT_12,
	LINE_OUT_13,
	LINE_OUT_14,
	LINE_OUT_15,
	LINE_OUT_16,

	LINE_RECORD_0,		// 16
	LINE_RECORD_1,
	LINE_RECORD_2,
	LINE_RECORD_3,
	LINE_RECORD_4,
	LINE_RECORD_5,
	LINE_RECORD_6,
	LINE_RECORD_7,

	// Custom
	LINE_ADAPTER,		// 24
	LINE_LSTREAM,		// 25
	// Sources
	LINE_NO_SOURCE,		// 27 must be the first source line

	LINE_IN_1,			// Used by LynxONE
	LINE_IN_2,

	LINE_PLAY_0,		// 30
	LINE_PLAY_1,
	LINE_PLAY_2,
	LINE_PLAY_3,
	LINE_PLAY_4,
	LINE_PLAY_5,
	LINE_PLAY_6,
	LINE_PLAY_7,

	LINE_PLAY_MIXA,		// 39
	LINE_PLAY_MIXB,
	LINE_PLAY_MIXC,
	LINE_PLAY_MIXD,

	LINE_ANALOGIN_1,	// 43
	LINE_ANALOGIN_2,
	LINE_ANALOGIN_3,
	LINE_ANALOGIN_4,
	LINE_ANALOGIN_5,
	LINE_ANALOGIN_6,
	LINE_ANALOGIN_7,
	LINE_ANALOGIN_8,
	LINE_ANALOGIN_9,
	LINE_ANALOGIN_10,
	LINE_ANALOGIN_11,
	LINE_ANALOGIN_12,
	LINE_ANALOGIN_13,
	LINE_ANALOGIN_14,
	LINE_ANALOGIN_15,
	LINE_ANALOGIN_16,

	LINE_DIGITALIN_1,	// 59
	LINE_DIGITALIN_2,
	LINE_DIGITALIN_3,
	LINE_DIGITALIN_4,
	LINE_DIGITALIN_5,
	LINE_DIGITALIN_6,
	LINE_DIGITALIN_7,
	LINE_DIGITALIN_8,
	LINE_DIGITALIN_9,
	LINE_DIGITALIN_10,
	LINE_DIGITALIN_11,
	LINE_DIGITALIN_12,
	LINE_DIGITALIN_13,
	LINE_DIGITALIN_14,
	LINE_DIGITALIN_15,
	LINE_DIGITALIN_16,

	LINE_ANALOGOUT_1,	// 75
	LINE_ANALOGOUT_2,
	LINE_ANALOGOUT_3,
	LINE_ANALOGOUT_4,
	LINE_ANALOGOUT_5,
	LINE_ANALOGOUT_6,
	LINE_ANALOGOUT_7,
	LINE_ANALOGOUT_8,
	LINE_ANALOGOUT_9,
	LINE_ANALOGOUT_10,
	LINE_ANALOGOUT_11,
	LINE_ANALOGOUT_12,
	LINE_ANALOGOUT_13,
	LINE_ANALOGOUT_14,
	LINE_ANALOGOUT_15,
	LINE_ANALOGOUT_16,

	LINE_DIGITALOUT_1,	// 91
	LINE_DIGITALOUT_2,
	LINE_DIGITALOUT_3,
	LINE_DIGITALOUT_4,
	LINE_DIGITALOUT_5,
	LINE_DIGITALOUT_6,
	LINE_DIGITALOUT_7,
	LINE_DIGITALOUT_8,
	LINE_DIGITALOUT_9,
	LINE_DIGITALOUT_10,
	LINE_DIGITALOUT_11,
	LINE_DIGITALOUT_12,
	LINE_DIGITALOUT_13,
	LINE_DIGITALOUT_14,
	LINE_DIGITALOUT_15,
	LINE_DIGITALOUT_16,

	NUM_LINES			// 107
};

#ifdef DEBUG
#define MIXERLINENAMES	\
char *gszLineNames[ NUM_LINES ] = {\
	"LINE_OUT_1",	\
	"LINE_OUT_2",	\
	"LINE_OUT_3",	\
	"LINE_OUT_4",	\
	"LINE_OUT_5",	\
	"LINE_OUT_6",	\
	"LINE_OUT_7",	\
	"LINE_OUT_8",	\
	"LINE_OUT_9",	\
	"LINE_OUT_10",	\
	"LINE_OUT_11",	\
	"LINE_OUT_12",	\
	"LINE_OUT_13",	\
	"LINE_OUT_14",	\
	"LINE_OUT_15",	\
	"LINE_OUT_16",	\
	"LINE_RECORD_0",	\
	"LINE_RECORD_1",	\
	"LINE_RECORD_2",	\
	"LINE_RECORD_3",	\
	"LINE_RECORD_4",	\
	"LINE_RECORD_5",	\
	"LINE_RECORD_6",	\
	"LINE_RECORD_7",	\
	"LINE_ADAPTER",	\
	"LINE_LSTREAM",	\
	"LINE_NO_SOURCE",	\
	"LINE_PLAY_0",	\
	"LINE_PLAY_1",	\
	"LINE_PLAY_2",	\
	"LINE_PLAY_3",	\
	"LINE_PLAY_4",	\
	"LINE_PLAY_5",	\
	"LINE_PLAY_6",	\
	"LINE_PLAY_7",	\
	"LINE_PLAY_MIXA",	\
	"LINE_PLAY_MIXB",	\
	"LINE_PLAY_MIXC",	\
	"LINE_PLAY_MIXD",	\
	"LINE_ANALOGIN_1", \
	"LINE_ANALOGIN_2", \
	"LINE_ANALOGIN_3", \
	"LINE_ANALOGIN_4", \
	"LINE_ANALOGIN_5", \
	"LINE_ANALOGIN_6", \
	"LINE_ANALOGIN_7", \
	"LINE_ANALOGIN_8", \
	"LINE_ANALOGIN_9", \
	"LINE_ANALOGIN_10", \
	"LINE_ANALOGIN_11", \
	"LINE_ANALOGIN_12", \
	"LINE_ANALOGIN_13", \
	"LINE_ANALOGIN_14", \
	"LINE_ANALOGIN_15", \
	"LINE_ANALOGIN_16", \
	"LINE_DIGITALIN_1", \
	"LINE_DIGITALIN_2", \
	"LINE_DIGITALIN_3", \
	"LINE_DIGITALIN_4", \
	"LINE_DIGITALIN_5", \
	"LINE_DIGITALIN_6", \
	"LINE_DIGITALIN_7", \
	"LINE_DIGITALIN_8", \
	"LINE_DIGITALIN_9", \
	"LINE_DIGITALIN_10", \
	"LINE_DIGITALIN_11", \
	"LINE_DIGITALIN_12", \
	"LINE_DIGITALIN_13", \
	"LINE_DIGITALIN_14", \
	"LINE_DIGITALIN_15", \
	"LINE_DIGITALIN_16", \
	"LINE_ANALOGOUT_1", \
	"LINE_ANALOGOUT_2", \
	"LINE_ANALOGOUT_3", \
	"LINE_ANALOGOUT_4", \
	"LINE_ANALOGOUT_5", \
	"LINE_ANALOGOUT_6", \
	"LINE_ANALOGOUT_7", \
	"LINE_ANALOGOUT_8", \
	"LINE_ANALOGOUT_9", \
	"LINE_ANALOGOUT_10", \
	"LINE_ANALOGOUT_11", \
	"LINE_ANALOGOUT_12", \
	"LINE_ANALOGOUT_13", \
	"LINE_ANALOGOUT_14", \
	"LINE_ANALOGOUT_15", \
	"LINE_ANALOGOUT_16", \
	"LINE_DIGITALOUT_1", \
	"LINE_DIGITALOUT_2", \
	"LINE_DIGITALOUT_3", \
	"LINE_DIGITALOUT_4", \
	"LINE_DIGITALOUT_5", \
	"LINE_DIGITALOUT_6", \
	"LINE_DIGITALOUT_7", \
	"LINE_DIGITALOUT_8", \
	"LINE_DIGITALOUT_9", \
	"LINE_DIGITALOUT_10", \
	"LINE_DIGITALOUT_11", \
	"LINE_DIGITALOUT_12", \
	"LINE_DIGITALOUT_13", \
	"LINE_DIGITALOUT_14", \
	"LINE_DIGITALOUT_15", \
	"LINE_DIGITALOUT_16", \
	}
#endif

/////////////////////////////////////////////////////////////////////////////
//	Mixer Control Types
/////////////////////////////////////////////////////////////////////////////
enum
{
	CONTROL_NUMCHANNELS=0,		// the number of channels this line has
	CONTROL_SOURCE,	// MUX
	CONTROL_SOURCE_LEFT,	// MUX
	CONTROL_SOURCE_RIGHT,	// MUX
	CONTROL_OVERLOAD,	// ULONG
	CONTROL_PEAKMETER,	// ULONG METER
	CONTROL_VOLUME,	// ULONG VOLUME
	CONTROL_MUTE,	// BOOLEAN MUTE
	CONTROL_DITHER,	// BOOLEAN
	CONTROL_MONITOR,	// BOOLEAN
	CONTROL_PHASE,	// BOOLEAN
	CONTROL_DITHER_DEPTH,	// MUX
	CONTROL_OVERRUN_COUNT,	// ULONG
	CONTROL_SAMPLE_COUNT,	// ULONG
	CONTROL_SAMPLE_FORMAT,	// ULONG
	CONTROL_INPUT_SOURCE,	// MUX
	CONTROL_CLOCKSOURCE,	// MUX
	CONTROL_CLOCKREFERENCE,	// MUX
	CONTROL_CLOCKRATE,	// ULONG
	CONTROL_WIDEWIREIN,	// BOOLEAN
	CONTROL_WIDEWIREOUT,	// BOOLEAN
	CONTROL_SYNCHROLOCK_STATUS,	// ULONG
	CONTROL_AUTOCLOCKSELECT,	// BOOLEAN
	CONTROL_DIGITAL_FORMAT,	// MUX
	CONTROL_SRC_MODE,	// MUX
	CONTROL_SRC_RATIO,	// ULONG
	CONTROL_DIGITALIN_RATE,	// ULONG
	CONTROL_DIGITALIN_MUTE_ON_ERROR,	// BOOLEAN
	CONTROL_DIGITALIN_STATUS,	// ULONG
	CONTROL_DIGITALOUT_STATUS,	// ULONG
	CONTROL_TRIM,	// MUX
	CONTROL_MONITOR_SOURCE,	// MUX
	CONTROL_LEVELS,	// BOOLEAN
	CONTROL_AIN12_TRIM,	// MUX
	CONTROL_AIN34_TRIM,	// MUX
	CONTROL_AIN56_TRIM,	// MUX
	CONTROL_AOUT12_TRIM,	// MUX
	CONTROL_AOUT34_TRIM,	// MUX
	CONTROL_AOUT56_TRIM,	// MUX
	CONTROL_FREQUENCY_COUNTER_1,	// ULONG
	CONTROL_FREQUENCY_COUNTER_2,	// ULONG
	CONTROL_FREQUENCY_COUNTER_3,	// ULONG
	CONTROL_FREQUENCY_COUNTER_4,	// ULONG
	CONTROL_FREQUENCY_COUNTER_5,	// ULONG
	CONTROL_FREQUENCY_COUNTER_6,	// ULONG
	CONTROL_FREQUENCY_COUNTER_7,	// ULONG
	CONTROL_FREQUENCY_COUNTER_8,	// ULONG
	CONTROL_FREQUENCY_COUNTER_9,	// ULONG
	CONTROL_FREQUENCY_COUNTER_10,	// ULONG
	CONTROL_FREQUENCY_COUNTER_11,	// ULONG
	CONTROL_FREQUENCY_COUNTER_12,	// ULONG
	CONTROL_FREQUENCY_COUNTER_13,	// ULONG
	CONTROL_SYNCIN_NTSC,	// BOOLEAN
	CONTROL_DIGITALIN1_STATUS,	// ULONG
	CONTROL_DIGITALIN1_RATE,	// ULONG
	CONTROL_DIGITALIN2_STATUS,	// ULONG
	CONTROL_DIGITALIN2_RATE,	// ULONG
	CONTROL_DIGITALIN3_STATUS,	// ULONG
	CONTROL_DIGITALIN3_RATE,	// ULONG
	CONTROL_DIGITALIN4_STATUS,	// ULONG
	CONTROL_DIGITALIN4_RATE,	// ULONG
	CONTROL_DIGITALIN5_STATUS,	// ULONG
	CONTROL_DIGITALIN5_RATE,	// ULONG
	CONTROL_DIGITALIN5_SRC_ENABLE,	// BOOLEAN
	CONTROL_DIGITALIN5_SRC_RATIO,	// ULONG
	CONTROL_DIGITALIN6_STATUS,	// ULONG
	CONTROL_DIGITALIN6_RATE,	// ULONG
	CONTROL_DIGITALIN6_SRC_ENABLE,	// BOOLEAN
	CONTROL_DIGITALIN6_SRC_RATIO,	// ULONG
	CONTROL_DIGITALIN7_STATUS,	// ULONG
	CONTROL_DIGITALIN7_RATE,	// ULONG
	CONTROL_DIGITALIN7_SRC_ENABLE,	// BOOLEAN
	CONTROL_DIGITALIN7_SRC_RATIO,	// ULONG
	CONTROL_DIGITALIN8_STATUS,	// ULONG
	CONTROL_DIGITALIN8_RATE,	// ULONG
	CONTROL_DIGITALIN8_SRC_ENABLE,	// BOOLEAN
	CONTROL_DIGITALIN8_SRC_RATIO,	// ULONG
	CONTROL_DIGITALOUT1_STATUS,	// ULONG
	CONTROL_DIGITALOUT2_STATUS,	// ULONG
	CONTROL_DIGITALOUT3_STATUS,	// ULONG
	CONTROL_DIGITALOUT4_STATUS,	// ULONG
	CONTROL_DIGITALOUT5_STATUS,	// ULONG
	CONTROL_DIGITALOUT6_STATUS,	// ULONG
	CONTROL_DIGITALOUT7_STATUS,	// ULONG
	CONTROL_DIGITALOUT8_STATUS,	// ULONG
	CONTROL_LTCIN_LOCKED,	// BOOLEAN
	CONTROL_LTCIN_DIRECTION,	// BOOLEAN
	CONTROL_LTCIN_DROPFRAME,	// BOOLEAN
	CONTROL_LTCIN_FRAMERATE,	// ULONG
	CONTROL_LTCIN_POSITION,	// ULONG
	CONTROL_LTCOUT_ENABLE,	// BOOLEAN
	CONTROL_LTCOUT_FRAMERATE,	// MUX
	CONTROL_LTCOUT_DROPFRAME,	// BOOLEAN
	CONTROL_LTCOUT_SYNCSOURCE,	// MUX
	CONTROL_LTCOUT_POSITION,	// ULONG
	CONTROL_LS1_DEVICEID,	// ULONG
	CONTROL_LS1_PCBREV,	// ULONG
	CONTROL_LS1_FIRMWAREREV,	// ULONG
	CONTROL_LS1_OUTSEL,	// MUX
	CONTROL_LS1_ADAT_CLKSRC,	// MUX
	CONTROL_LS1_ADAT_IN1_LOCK,	// BOOLEAN
	CONTROL_LS1_ADAT_IN2_LOCK,	// BOOLEAN
	CONTROL_LS1_ADAT_POSITION,	// ULONG
	CONTROL_LS1_ADAT_CUEPOINT_ENABLE,	// BOOLEAN
	CONTROL_LS1_ADAT_CUEPOINT,	// ULONG
	CONTROL_LS1_AES_CLKSRC,	// MUX
	CONTROL_LS1_AES_WIDEWIRE,	// BOOLEAN
	CONTROL_LS1_D1_FORMAT,	// MUX
	CONTROL_LS1_DI1_SRC_MODE,	// MUX
	CONTROL_LS1_DI1_RATE,	// ULONG
	CONTROL_LS1_DI1_SRC_RATIO,	// ULONG
	CONTROL_LS1_DI1_STATUS,	// ULONG
	CONTROL_LS1_DO1_STATUS,	// ULONG
	CONTROL_LS1_D2_FORMAT,	// MUX
	CONTROL_LS1_DI2_SRC_MODE,	// MUX
	CONTROL_LS1_DI2_RATE,	// ULONG
	CONTROL_LS1_DI2_SRC_RATIO,	// ULONG
	CONTROL_LS1_DI2_STATUS,	// ULONG
	CONTROL_LS1_DO2_STATUS,	// ULONG
	CONTROL_LS1_D3_FORMAT,	// MUX
	CONTROL_LS1_DI3_SRC_MODE,	// MUX
	CONTROL_LS1_DI3_RATE,	// ULONG
	CONTROL_LS1_DI3_SRC_RATIO,	// ULONG
	CONTROL_LS1_DI3_STATUS,	// ULONG
	CONTROL_LS1_DO3_STATUS,	// ULONG
	CONTROL_LS1_D4_FORMAT,	// MUX
	CONTROL_LS1_DI4_SRC_MODE,	// MUX
	CONTROL_LS1_DI4_RATE,	// ULONG
	CONTROL_LS1_DI4_SRC_RATIO,	// ULONG
	CONTROL_LS1_DI4_STATUS,	// ULONG
	CONTROL_LS1_DO4_STATUS,	// ULONG
	CONTROL_LS2_DEVICEID,	// ULONG
	CONTROL_LS2_PCBREV,	// ULONG
	CONTROL_LS2_FIRMWAREREV,	// ULONG
	CONTROL_LS2_OUTSEL,	// MUX
	CONTROL_LS2_ADAT_CLKSRC,	// MUX
	CONTROL_LS2_ADAT_IN1_LOCK,	// BOOLEAN
	CONTROL_LS2_ADAT_IN2_LOCK,	// BOOLEAN
	CONTROL_LS2_ADAT_POSITION,	// ULONG
	CONTROL_LS2_ADAT_CUEPOINT_ENABLE,	// BOOLEAN
	CONTROL_LS2_ADAT_CUEPOINT,	// ULONG
	CONTROL_LS2_AES_CLKSRC,	// MUX
	CONTROL_LS2_AES_WIDEWIRE,	// BOOLEAN
	CONTROL_LS2_D1_FORMAT,	// MUX
	CONTROL_LS2_DI1_SRC_MODE,	// MUX
	CONTROL_LS2_DI1_RATE,	// ULONG
	CONTROL_LS2_DI1_SRC_RATIO,	// ULONG
	CONTROL_LS2_DI1_STATUS,	// ULONG
	CONTROL_LS2_DO1_STATUS,	// ULONG
	CONTROL_LS2_D2_FORMAT,	// MUX
	CONTROL_LS2_DI2_SRC_MODE,	// MUX
	CONTROL_LS2_DI2_RATE,	// ULONG
	CONTROL_LS2_DI2_SRC_RATIO,	// ULONG
	CONTROL_LS2_DI2_STATUS,	// ULONG
	CONTROL_LS2_DO2_STATUS,	// ULONG
	CONTROL_LS2_D3_FORMAT,	// MUX
	CONTROL_LS2_DI3_SRC_MODE,	// MUX
	CONTROL_LS2_DI3_RATE,	// ULONG
	CONTROL_LS2_DI3_SRC_RATIO,	// ULONG
	CONTROL_LS2_DI3_STATUS,	// ULONG
	CONTROL_LS2_DO3_STATUS,	// ULONG
	CONTROL_LS2_D4_FORMAT,	// MUX
	CONTROL_LS2_DI4_SRC_MODE,	// MUX
	CONTROL_LS2_DI4_RATE,	// ULONG
	CONTROL_LS2_DI4_SRC_RATIO,	// ULONG
	CONTROL_LS2_DI4_STATUS,	// ULONG
	CONTROL_LS2_DO4_STATUS,	// ULONG
	CONTROL_FP_METER_SOURCE,	// MUX
	CONTROL_LSLOT_OUT_SOURCE,	// MUX
	CONTROL_TRIM_AIN_1_4,	// MUX
	CONTROL_TRIM_AIN_5_8,	// MUX
	CONTROL_TRIM_AIN_9_12,	// MUX
	CONTROL_TRIM_AIN_13_16,	// MUX
	CONTROL_TRIM_AOUT_1_4,	// MUX
	CONTROL_TRIM_AOUT_5_8,	// MUX
	CONTROL_TRIM_AOUT_9_12,	// MUX
	CONTROL_TRIM_AOUT_13_16,	// MUX
	CONTROL_VOLUMEA,	// ULONG
	CONTROL_MUTEA,	// BOOLEAN
	CONTROL_SOURCEA,	// MUX
	CONTROL_VOLUMEB,	// ULONG
	CONTROL_MUTEB,	// BOOLEAN
	CONTROL_SOURCEB,	// MUX
	CONTROL_DITHER_TYPE,	// MUX
	CONTROL_PLAY_DITHER,	// MUX
	CONTROL_RECORD_DITHER,	// MUX
	CONTROL_ADDA_RECALIBRATE,	// BOOLEAN
	CONTROL_AUTO_RECALIBRATE,	// BOOLEAN
	CONTROL_AIN12_HPF,	// BOOLEAN
	CONTROL_AIN34_HPF,	// BOOLEAN
	CONTROL_AIN56_HPF,	// BOOLEAN
	CONTROL_ADHIPASSFILTER,	// BOOLEAN
	CONTROL_DA_AUTOMUTE,	// BOOLEAN
	CONTROL_DA_DEEMPHASIS,	// BOOLEAN
	CONTROL_SYNCHROLOCK_ENABLE,	// BOOLEAN
	CONTROL_DIGITALIN_SRC_MATCHPHASE,	// BOOLEAN
	CONTROL_SYNCSTART,	// BOOLEAN
	CONTROL_MTC_SOURCE,	// MUX
	CONTROL_LSTREAM_DUAL_INTERNAL,	// BOOLEAN
	CONTROL_MONITOR_OFF_PLAY,	// BOOLEAN
	CONTROL_MONITOR_ON_RECORD,	// BOOLEAN
	CONTROL_DEVICEID,	// ULONG
	CONTROL_PCBREV,	// ULONG
	CONTROL_FIRMWAREREV,	// ULONG
	CONTROL_FIRMWAREDATE,	// ULONG
	CONTROL_MINSOFTWAREREV,	// ULONG
	CONTROL_SERIALNUMBER,	// ULONG
	CONTROL_MFGDATE,	// ULONG
	CONTROL_FAST_SHARED_CONTROLS,	// ULONG
	CONTROL_SLOW_SHARED_CONTROLS,	// ULONG
	CONTROL_MIXER_RESTORE_SCENE,	// ULONG
	CONTROL_MIXER_SAVE_SCENE,	// ULONG
	CONTROL_MIXER_LOCK,	// BOOLEAN
	NUM_CONTROLS				// See Controls.xls
};

#ifdef DEBUG
#define MIXERCONTROLNAMES	\
char *gszControlNames[ NUM_CONTROLS ] = {	\
	"CONTROL_NUMCHANNELS",	\
	"CONTROL_SOURCE", \
	"CONTROL_SOURCE_LEFT", \
	"CONTROL_SOURCE_RIGHT", \
	"CONTROL_OVERLOAD", \
	"CONTROL_PEAKMETER", \
	"CONTROL_VOLUME", \
	"CONTROL_MUTE", \
	"CONTROL_DITHER", \
	"CONTROL_MONITOR", \
	"CONTROL_PHASE", \
	"CONTROL_DITHER_DEPTH", \
	"CONTROL_OVERRUN_COUNT", \
	"CONTROL_SAMPLE_COUNT", \
	"CONTROL_SAMPLE_FORMAT", \
	"CONTROL_INPUT_SOURCE", \
	"CONTROL_CLOCKSOURCE", \
	"CONTROL_CLOCKREFERENCE", \
	"CONTROL_CLOCKRATE", \
	"CONTROL_WIDEWIREIN", \
	"CONTROL_WIDEWIREOUT", \
	"CONTROL_SYNCHROLOCK_STATUS", \
	"CONTROL_AUTOCLOCKSELECT", \
	"CONTROL_DIGITAL_FORMAT", \
	"CONTROL_SRC_MODE", \
	"CONTROL_SRC_RATIO", \
	"CONTROL_DIGITALIN_RATE", \
	"CONTROL_DIGITALIN_MUTE_ON_ERROR", \
	"CONTROL_DIGITALIN_STATUS", \
	"CONTROL_DIGITALOUT_STATUS", \
	"CONTROL_TRIM", \
	"CONTROL_MONITOR_SOURCE", \
	"CONTROL_LEVELS", \
	"CONTROL_AIN12_TRIM", \
	"CONTROL_AIN34_TRIM", \
	"CONTROL_AIN56_TRIM", \
	"CONTROL_AOUT12_TRIM", \
	"CONTROL_AOUT34_TRIM", \
	"CONTROL_AOUT56_TRIM", \
	"CONTROL_FREQUENCY_COUNTER_1", \
	"CONTROL_FREQUENCY_COUNTER_2", \
	"CONTROL_FREQUENCY_COUNTER_3", \
	"CONTROL_FREQUENCY_COUNTER_4", \
	"CONTROL_FREQUENCY_COUNTER_5", \
	"CONTROL_FREQUENCY_COUNTER_6", \
	"CONTROL_FREQUENCY_COUNTER_7", \
	"CONTROL_FREQUENCY_COUNTER_8", \
	"CONTROL_FREQUENCY_COUNTER_9", \
	"CONTROL_FREQUENCY_COUNTER_10", \
	"CONTROL_FREQUENCY_COUNTER_11", \
	"CONTROL_FREQUENCY_COUNTER_12", \
	"CONTROL_FREQUENCY_COUNTER_13", \
	"CONTROL_SYNCIN_NTSC", \
	"CONTROL_DIGITALIN1_STATUS", \
	"CONTROL_DIGITALIN1_RATE", \
	"CONTROL_DIGITALIN2_STATUS", \
	"CONTROL_DIGITALIN2_RATE", \
	"CONTROL_DIGITALIN3_STATUS", \
	"CONTROL_DIGITALIN3_RATE", \
	"CONTROL_DIGITALIN4_STATUS", \
	"CONTROL_DIGITALIN4_RATE", \
	"CONTROL_DIGITALIN5_STATUS", \
	"CONTROL_DIGITALIN5_RATE", \
	"CONTROL_DIGITALIN5_SRC_ENABLE", \
	"CONTROL_DIGITALIN5_SRC_RATIO", \
	"CONTROL_DIGITALIN6_STATUS", \
	"CONTROL_DIGITALIN6_RATE", \
	"CONTROL_DIGITALIN6_SRC_ENABLE", \
	"CONTROL_DIGITALIN6_SRC_RATIO", \
	"CONTROL_DIGITALIN7_STATUS", \
	"CONTROL_DIGITALIN7_RATE", \
	"CONTROL_DIGITALIN7_SRC_ENABLE", \
	"CONTROL_DIGITALIN7_SRC_RATIO", \
	"CONTROL_DIGITALIN8_STATUS", \
	"CONTROL_DIGITALIN8_RATE", \
	"CONTROL_DIGITALIN8_SRC_ENABLE", \
	"CONTROL_DIGITALIN8_SRC_RATIO", \
	"CONTROL_DIGITALOUT1_STATUS", \
	"CONTROL_DIGITALOUT2_STATUS", \
	"CONTROL_DIGITALOUT3_STATUS", \
	"CONTROL_DIGITALOUT4_STATUS", \
	"CONTROL_DIGITALOUT5_STATUS", \
	"CONTROL_DIGITALOUT6_STATUS", \
	"CONTROL_DIGITALOUT7_STATUS", \
	"CONTROL_DIGITALOUT8_STATUS", \
	"CONTROL_LTCIN_LOCKED", \
	"CONTROL_LTCIN_DIRECTION", \
	"CONTROL_LTCIN_DROPFRAME", \
	"CONTROL_LTCIN_FRAMERATE", \
	"CONTROL_LTCIN_POSITION", \
	"CONTROL_LTCOUT_ENABLE", \
	"CONTROL_LTCOUT_FRAMERATE", \
	"CONTROL_LTCOUT_DROPFRAME", \
	"CONTROL_LTCOUT_SYNCSOURCE", \
	"CONTROL_LTCOUT_POSITION", \
	"CONTROL_LS1_DEVICEID", \
	"CONTROL_LS1_PCBREV", \
	"CONTROL_LS1_FIRMWAREREV", \
	"CONTROL_LS1_OUTSEL", \
	"CONTROL_LS1_ADAT_CLKSRC", \
	"CONTROL_LS1_ADAT_IN1_LOCK", \
	"CONTROL_LS1_ADAT_IN2_LOCK", \
	"CONTROL_LS1_ADAT_POSITION", \
	"CONTROL_LS1_ADAT_CUEPOINT_ENABLE", \
	"CONTROL_LS1_ADAT_CUEPOINT", \
	"CONTROL_LS1_AES_CLKSRC", \
	"CONTROL_LS1_AES_WIDEWIRE", \
	"CONTROL_LS1_D1_FORMAT", \
	"CONTROL_LS1_DI1_SRC_MODE", \
	"CONTROL_LS1_DI1_RATE", \
	"CONTROL_LS1_DI1_SRC_RATIO", \
	"CONTROL_LS1_DI1_STATUS", \
	"CONTROL_LS1_DO1_STATUS", \
	"CONTROL_LS1_D2_FORMAT", \
	"CONTROL_LS1_DI2_SRC_MODE", \
	"CONTROL_LS1_DI2_RATE", \
	"CONTROL_LS1_DI2_SRC_RATIO", \
	"CONTROL_LS1_DI2_STATUS", \
	"CONTROL_LS1_DO2_STATUS", \
	"CONTROL_LS1_D3_FORMAT", \
	"CONTROL_LS1_DI3_SRC_MODE", \
	"CONTROL_LS1_DI3_RATE", \
	"CONTROL_LS1_DI3_SRC_RATIO", \
	"CONTROL_LS1_DI3_STATUS", \
	"CONTROL_LS1_DO3_STATUS", \
	"CONTROL_LS1_D4_FORMAT", \
	"CONTROL_LS1_DI4_SRC_MODE", \
	"CONTROL_LS1_DI4_RATE", \
	"CONTROL_LS1_DI4_SRC_RATIO", \
	"CONTROL_LS1_DI4_STATUS", \
	"CONTROL_LS1_DO4_STATUS", \
	"CONTROL_LS2_DEVICEID", \
	"CONTROL_LS2_PCBREV", \
	"CONTROL_LS2_FIRMWAREREV", \
	"CONTROL_LS2_OUTSEL", \
	"CONTROL_LS2_ADAT_CLKSRC", \
	"CONTROL_LS2_ADAT_IN1_LOCK", \
	"CONTROL_LS2_ADAT_IN2_LOCK", \
	"CONTROL_LS2_ADAT_POSITION", \
	"CONTROL_LS2_ADAT_CUEPOINT_ENABLE", \
	"CONTROL_LS2_ADAT_CUEPOINT", \
	"CONTROL_LS2_AES_CLKSRC", \
	"CONTROL_LS2_AES_WIDEWIRE", \
	"CONTROL_LS2_D1_FORMAT", \
	"CONTROL_LS2_DI1_SRC_MODE", \
	"CONTROL_LS2_DI1_RATE", \
	"CONTROL_LS2_DI1_SRC_RATIO", \
	"CONTROL_LS2_DI1_STATUS", \
	"CONTROL_LS2_DO1_STATUS", \
	"CONTROL_LS2_D2_FORMAT", \
	"CONTROL_LS2_DI2_SRC_MODE", \
	"CONTROL_LS2_DI2_RATE", \
	"CONTROL_LS2_DI2_SRC_RATIO", \
	"CONTROL_LS2_DI2_STATUS", \
	"CONTROL_LS2_DO2_STATUS", \
	"CONTROL_LS2_D3_FORMAT", \
	"CONTROL_LS2_DI3_SRC_MODE", \
	"CONTROL_LS2_DI3_RATE", \
	"CONTROL_LS2_DI3_SRC_RATIO", \
	"CONTROL_LS2_DI3_STATUS", \
	"CONTROL_LS2_DO3_STATUS", \
	"CONTROL_LS2_D4_FORMAT", \
	"CONTROL_LS2_DI4_SRC_MODE", \
	"CONTROL_LS2_DI4_RATE", \
	"CONTROL_LS2_DI4_SRC_RATIO", \
	"CONTROL_LS2_DI4_STATUS", \
	"CONTROL_LS2_DO4_STATUS", \
	"CONTROL_FP_METER_SOURCE", \
	"CONTROL_LSLOT_OUT_SOURCE", \
	"CONTROL_TRIM_AIN_1_4", \
	"CONTROL_TRIM_AIN_5_8", \
	"CONTROL_TRIM_AIN_9_12", \
	"CONTROL_TRIM_AIN_13_16", \
	"CONTROL_TRIM_AOUT_1_4", \
	"CONTROL_TRIM_AOUT_5_8", \
	"CONTROL_TRIM_AOUT_9_12", \
	"CONTROL_TRIM_AOUT_13_16", \
	"CONTROL_VOLUMEA", \
	"CONTROL_MUTEA", \
	"CONTROL_SOURCEA", \
	"CONTROL_VOLUMEB", \
	"CONTROL_MUTEB", \
	"CONTROL_SOURCEB", \
	"CONTROL_DITHER_TYPE", \
	"CONTROL_PLAY_DITHER", \
	"CONTROL_RECORD_DITHER", \
	"CONTROL_ADDA_RECALIBRATE", \
	"CONTROL_AUTO_RECALIBRATE", \
	"CONTROL_AIN12_HPF", \
	"CONTROL_AIN34_HPF", \
	"CONTROL_AIN56_HPF", \
	"CONTROL_ADHIPASSFILTER", \
	"CONTROL_DA_AUTOMUTE", \
	"CONTROL_DA_DEEMPHASIS", \
	"CONTROL_SYNCHROLOCK_ENABLE", \
	"CONTROL_DIGITALIN_SRC_MATCHPHASE", \
	"CONTROL_SYNCSTART", \
	"CONTROL_MTC_SOURCE", \
	"CONTROL_LSTREAM_DUAL_INTERNAL", \
	"CONTROL_MONITOR_OFF_PLAY", \
	"CONTROL_MONITOR_ON_RECORD", \
	"CONTROL_DEVICEID", \
	"CONTROL_PCBREV", \
	"CONTROL_FIRMWAREREV", \
	"CONTROL_FIRMWAREDATE", \
	"CONTROL_MINSOFTWAREREV", \
	"CONTROL_SERIALNUMBER", \
	"CONTROL_MFGDATE", \
	"CONTROL_FAST_SHARED_CONTROLS", \
	"CONTROL_SLOW_SHARED_CONTROLS", \
	"CONTROL_MIXER_RESTORE_SCENE", \
	"CONTROL_MIXER_SAVE_SCENE", \
	"CONTROL_MIXER_LOCK", \
	}
#endif

#endif	// _CONTROLLIST_H
