#ifndef HAL_STATUS_CODES
#define HAL_STATUS_CODES
/////////////////////////////////////////////////////////////////////////////
//	Status Codes
/////////////////////////////////////////////////////////////////////////////
enum
{
	HSTATUS_OK=0,
	HSTATUS_CANNOT_FIND_ADAPTER,
	HSTATUS_CANNOT_MAP_ADAPTER,
	HSTATUS_CANNOT_UNMAP_ADAPTER,
	HSTATUS_ADAPTER_NOT_OPEN,
	HSTATUS_ADAPTER_NOT_FOUND,
	HSTATUS_BAD_ADAPTER_RAM,
	HSTATUS_INCORRECT_FIRMWARE,
	HSTATUS_DOWNLOAD_FAILED,
	HSTATUS_HW_NOT_RESPONDING,
	HSTATUS_INVALID_PARAMETER,
	HSTATUS_INVALID_MODE,
	HSTATUS_INVALID_FORMAT,
	HSTATUS_INVALID_ADDRESS,
	HSTATUS_INVALID_CLOCK_SOURCE,
	HSTATUS_INVALID_SAMPLERATE,
	HSTATUS_INVALID_MIXER_LINE,
	HSTATUS_INVALID_MIXER_CONTROL,
	HSTATUS_INVALID_MIXER_VALUE,
	HSTATUS_INSUFFICIENT_RESOURCES,
	HSTATUS_BUFFER_FULL,
	HSTATUS_ALREADY_IN_USE,
	HSTATUS_TIMEOUT,
	HSTATUS_MIXER_LOCKED,
	HSTATUS_SERVICE_NOT_REQUIRED,
	HSTATUS_MIDI1_SERVICE_REQUIRED,	// QFM
	HSTATUS_MIDI2_SERVICE_REQUIRED,	// ADAT MIDI SYNCIN
	NUM_HSTATUS_CODES
};

#endif
